const fs = require('fs');
let content = fs.readFileSync('src/components/ApartmentModal.tsx', 'utf8');
content = content.replace(/\{Math\.round\(\(d\.price as number\) \/ 1000\)\}/g, '{Math.round((Number((d as Record<string, number>).price) || 0) / 1000)}');
content = content.replace(/\{d\.name\}/g, '{String((d as Record<string, string>).name)}');
content = content.replace(/\{d\.value\}/g, '{Number((d as Record<string, number>).value)}');
content = content.replace(/data: unknown \}/g, 'data: Record<string, unknown> }');
content = content.replace(/\(rechartProps as Record<string, Record<string, unknown>>\)/g, '(rechartProps as { xAxisMap?: Record<string, unknown>; yAxisMap?: Record<string, unknown> })');
content = content.replace(/\{hoveredDot\.data\.name\}/g, '{String(hoveredDot.data.name)}');
content = content.replace(/\{hoveredDot\.data\.value\}/g, '{Number(hoveredDot.data.value)}');
content = content.replace(/\{new Date\(minTimestamp\)\}/g, '{new Date(Number(minTimestamp))}');
content = content.replace(/formatter=\{\(value: number \| string \| undefined\)/g, 'formatter={(value: unknown)');
content = content.replace("[`${Number(value).toLocaleString()} 만원`", "[`${Number(value || 0).toLocaleString()} 만원`");
content = content.replace(/\{Math\.round\(\(d as Record<string, number>\)\.price \/ 1000\)\}/g, '{Math.round(((d as Record<string, number>).price || 0) / 1000)}');
fs.writeFileSync('src/components/ApartmentModal.tsx', content);

let adminAppt = fs.readFileSync('src/app/admin/apartments/[name]/page.tsx', 'utf8');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.dong/g, 'String((aptMeta[name] as Record<string, unknown>)?.dong || "")');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.txKey/g, 'String((aptMeta[name] as Record<string, unknown>)?.txKey || "")');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.maxFloor/g, 'Number((aptMeta[name] as Record<string, unknown>)?.maxFloor || 0)');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.isPublicRental/g, 'Boolean((aptMeta[name] as Record<string, unknown>)?.isPublicRental)');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.householdCount/g, 'Number((aptMeta[name] as Record<string, unknown>)?.householdCount || 0)');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.yearBuilt/g, 'String((aptMeta[name] as Record<string, unknown>)?.yearBuilt || "")');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.brand/g, 'String((aptMeta[name] as Record<string, unknown>)?.brand || "")');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.ticker/g, 'String((aptMeta[name] as Record<string, unknown>)?.ticker || "")');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.far/g, 'Number((aptMeta[name] as Record<string, unknown>)?.far || 0)');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.bcr/g, 'Number((aptMeta[name] as Record<string, unknown>)?.bcr || 0)');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.parkingCount/g, 'Number((aptMeta[name] as Record<string, unknown>)?.parkingCount || 0)');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.parkingPerHousehold/g, 'Number((aptMeta[name] as Record<string, unknown>)?.parkingPerHousehold || 0)');
adminAppt = adminAppt.replace(/\(aptMeta\[name\] as Record<string, unknown>\)\?\.coordinates/g, '((aptMeta[name] as Record<string, unknown>)?.coordinates as {lat: number, lng: number})');
adminAppt = adminAppt.replace(/apt\.dong/g, '(apt as Record<string, unknown>)?.dong');
adminAppt = adminAppt.replace(/apt\.txKey/g, '(apt as Record<string, unknown>)?.txKey');
adminAppt = adminAppt.replace(/apt\.maxFloor/g, '(apt as Record<string, unknown>)?.maxFloor');
adminAppt = adminAppt.replace(/apt\.isPublicRental/g, '(apt as Record<string, unknown>)?.isPublicRental');
adminAppt = adminAppt.replace(/apt\.householdCount/g, '(apt as Record<string, unknown>)?.householdCount');
adminAppt = adminAppt.replace(/apt\.yearBuilt/g, '(apt as Record<string, unknown>)?.yearBuilt');
adminAppt = adminAppt.replace(/apt\.brand/g, '(apt as Record<string, unknown>)?.brand');
adminAppt = adminAppt.replace(/apt\.ticker/g, '(apt as Record<string, unknown>)?.ticker');
adminAppt = adminAppt.replace(/apt\.far/g, '(apt as Record<string, unknown>)?.far');
adminAppt = adminAppt.replace(/apt\.bcr/g, '(apt as Record<string, unknown>)?.bcr');
adminAppt = adminAppt.replace(/apt\.parkingCount/g, '(apt as Record<string, unknown>)?.parkingCount');
adminAppt = adminAppt.replace(/apt\.coordinates\?\.lat/g, '((apt as Record<string, Record<string, number>>)?.coordinates)?.lat');
adminAppt = adminAppt.replace(/apt\.coordinates\?\.lng/g, '((apt as Record<string, Record<string, number>>)?.coordinates)?.lng');
adminAppt = adminAppt.replace(/\[key\] = value;/g, '[key] = value;');
fs.writeFileSync('src/app/admin/apartments/[name]/page.tsx', adminAppt);

let lounge = fs.readFileSync('src/app/lounge/[id]/page.tsx', 'utf8');
lounge = lounge.replace(/\{post\.title\}/g, '{String(post.title)}');
lounge = lounge.replace(/\{post\.author\}/g, '{String(post.author)}');
lounge = lounge.replace(/\{post\.category\}/g, '{String(post.category)}');
lounge = lounge.replace(/\{post\.verifiedApartment\}/g, '{String(post.verifiedApartment)}');
lounge = lounge.replace(/\{post\.verificationLevel\}/g, '{String(post.verificationLevel)}');
lounge = lounge.replace(/\{post\.createdAt\}/g, '{String(post.createdAt)}');
lounge = lounge.replace(/\{post\.likes\}/g, '{Number(post.likes)}');
fs.writeFileSync('src/app/lounge/[id]/page.tsx', lounge);

let page = fs.readFileSync('src/app/admin/page.tsx', 'utf8');
page = page.replace(/apt\.dong/g, '(apt as Record<string, unknown>)?.dong');
page = page.replace(/apt\.txKey/g, '(apt as Record<string, unknown>)?.txKey');
page = page.replace(/apt\.maxFloor/g, '(apt as Record<string, unknown>)?.maxFloor');
page = page.replace(/apt\.isPublicRental/g, '(apt as Record<string, unknown>)?.isPublicRental');
page = page.replace(/apt\.householdCount/g, '(apt as Record<string, unknown>)?.householdCount');
page = page.replace(/apt\.yearBuilt/g, '(apt as Record<string, unknown>)?.yearBuilt');
page = page.replace(/apt\.brand/g, '(apt as Record<string, unknown>)?.brand');
page = page.replace(/apt\.ticker/g, '(apt as Record<string, unknown>)?.ticker');
fs.writeFileSync('src/app/admin/page.tsx', page);
