/**
 * 정적 아파트 데이터 — 빌드 타임에 포함되어 API 호출 없이 즉시 사용 가능
 * 
 * ⚠️ 이 파일은 자동 생성됩니다. 직접 수정하지 마세요!
 * 동기화: npm run sync-apartments
 * 마지막 동기화: 2026-04-19
 */

export interface StaticApartment {
  name: string;
  dong: string;
  householdCount?: number;
  yearBuilt?: string;
  brand?: string;
}

/** 동별 아파트 데이터 (정렬됨) */
export const APARTMENTS_BY_DONG: Record<string, StaticApartment[]> = {
  '능동': [
    { name: '능동마을 주공', dong: '능동' },
    { name: '능동마을 주공 7단지', dong: '능동' },
    { name: '능동역 경남아너스빌', dong: '능동', householdCount: 455, yearBuilt: '2008', brand: '경남기업' },
    { name: '능동역 센트럴 경남아너스빌', dong: '능동', householdCount: 641, yearBuilt: '2008', brand: '경남건설' },
    { name: '능동역 이지더원', dong: '능동', householdCount: 542, yearBuilt: '2008', brand: '남흥건설' },
    { name: '동탄능동마을 상록예가', dong: '능동' },
    { name: '동탄숲속마을 능동역 리체더포레스트', dong: '능동', householdCount: 562, yearBuilt: '2008', brand: '풍성주택' },
    { name: '동탄푸른마을 두산위브', dong: '능동' },
    { name: '숲속마을 동탄 광명메이루즈', dong: '능동' },
    { name: '숲속마을 동탄 모아미래도 1단지', dong: '능동' },
    { name: '숲속마을 동탄 모아미래도 2단지', dong: '능동' },
    { name: '숲속마을 동탄 자연앤데시앙', dong: '능동' },
    { name: '에스원 스마트빌', dong: '능동' },
    { name: '푸른마을 동탄 모아미래도', dong: '능동' },
    { name: '푸른마을 동탄 신일해피트리', dong: '능동' },
    { name: '푸른마을 포스코더샵 2차', dong: '능동' },
  ],
  '목동': [
    { name: '금강펜테리움 센트럴파크 4차', dong: '목동', householdCount: 1195, yearBuilt: '2018', brand: '금강주택' },
    { name: '동탄 동원로얄듀크 2차', dong: '목동' },
    { name: '동탄2신도시 베라체', dong: '목동' },
    { name: '동탄2신도시 호반베르디움 2차', dong: '목동' },
    { name: '르파비스', dong: '목동' },
    { name: '한신더휴', dong: '목동' },
    { name: '호반베르디움 센트럴포레', dong: '목동' },
    { name: '힐스테이트 동탄', dong: '목동' },
    { name: 'e편한세상 동탄', dong: '목동' },
  ],
  '반송동': [
    { name: '동탄 금호어울림', dong: '반송동' },
    { name: '동탄나루마을 동탄역 유보라', dong: '반송동' },
    { name: '동탄나루마을 동탄한화꿈에그린', dong: '반송동' },
    { name: '동탄나루마을 신도브래뉴', dong: '반송동' },
    { name: '동탄나루마을 한화꿈에그린', dong: '반송동' },
    { name: '동탄센트럴포레스트', dong: '반송동' },
    { name: '동탄스카이뷰', dong: '반송동' },
    { name: '동탄시범다은마을 메타역세권', dong: '반송동' },
    { name: '동탄시범다은마을 센트럴힐', dong: '반송동' },
    { name: '동탄시범다은마을 월드메르디앙', dong: '반송동' },
    { name: '동탄시범한빛마을 KCC스위첸', dong: '반송동' },
    { name: '동탄우림필유 타운하우스', dong: '반송동' },
    { name: '동탄위버폴리스', dong: '반송동' },
    { name: '동탄파라곤', dong: '반송동' },
    { name: '동탄파라곤 II', dong: '반송동' },
    { name: '동탄플래티넘', dong: '반송동' },
    { name: '동탄현대 하이페리온', dong: '반송동' },
    { name: '메타폴리스', dong: '반송동' },
    { name: '반탄솔빛마을 신도브래뉴', dong: '반송동' },
    { name: '새강마을 휴먼시아 5단지2', dong: '반송동' },
    { name: '서해더블루', dong: '반송동' },
    { name: '서해더블루 90-2번지', dong: '반송동' },
    { name: '서해더블루 93-8번지', dong: '반송동' },
    { name: '센트럴SE타운', dong: '반송동' },
    { name: '솔빛마을 경남아너스빌', dong: '반송동' },
    { name: '솔빛마을 동탄쌍용예가', dong: '반송동' },
    { name: '솔빛마을 서해그랑블', dong: '반송동' },
    { name: '시범나루마을 동탄역 UBO', dong: '반송동' },
    { name: '시범다은마을 동탄포스코더샵', dong: '반송동' },
    { name: '시범다은마을 삼성래미안', dong: '반송동' },
    { name: '시범다은마을 우남퍼스트빌', dong: '반송동' },
    { name: '시범한빛마을 동탄삼부르네상스', dong: '반송동' },
    { name: '시범한빛마을 한화꿈에그린', dong: '반송동' },
    { name: '시범한빛��을 동탄아이파크', dong: '반송동' },
    { name: '에스원센트로벨', dong: '반송동' },
    { name: '엔터프라임빌딩', dong: '반송동' },
  ],
  '산척동': [
    { name: '그린힐 반도유보라 아이비파크 10.0', dong: '산척동', householdCount: 1241, yearBuilt: '2018', brand: '반도건설' },
    { name: '더레이크시티 부영 2단지', dong: '산척동' },
    { name: '더레이크파크뷰', dong: '산척동' },
    { name: '동탄 꿈의숲 자연앤데시앙', dong: '산척동' },
    { name: '동탄 더레이크팰리스', dong: '산척동' },
    { name: '동탄 더샵 레이크에듀타운', dong: '산척동' },
    { name: '동탄 포레파크 자연앤푸르지오', dong: '산척동' },
    { name: '동탄호수공원 금강펜테리움 센트럴파크 2차', dong: '산척동' },
    { name: '동탄호수공원역 레이크시티', dong: '산척동' },
    { name: '레이크힐 반도유보라 아이비파크 10.0', dong: '산척동' },
    { name: '서희스타힐스 엔에이치에프', dong: '산척동' },
    { name: '중흥에스클래스 에듀하이', dong: '산척동' },
    { name: '호수공원역 센트럴시티', dong: '산척동' },
    { name: '호수공원역 센트리체', dong: '산척동' },
  ],
  '석우동': [
    { name: '예당마을 롯데캐슬', dong: '석우동' },
    { name: '예당마을 신일유토빌', dong: '석우동' },
    { name: '예당마을 우미린 제일풍경채', dong: '석우동' },
    { name: '예당마을 푸르지오', dong: '석우동', householdCount: 978, yearBuilt: '2008', brand: '대우건설' },
  ],
  '송동': [
    { name: '동탄 레이크자이 더테라스', dong: '송동' },
    { name: '동탄2 LH 26단지', dong: '송동' },
    { name: '동탄2신도시 하우스디 더레이크', dong: '송동' },
    { name: '동탄린스트라우스 더레이크', dong: '송동' },
  ],
  '신동': [
    { name: '동탄 파라곤 3차', dong: '신동' },
    { name: '동탄 GWEN160', dong: '신동' },
    { name: '동탄2 디에트르포레', dong: '신동' },
    { name: '동탄2신도시 C27BL', dong: '신동' },
    { name: '동탄2신도시 C29BL 우성더르네상스', dong: '신동' },
    { name: '동탄신도시 금강펜테리움 6차', dong: '신동' },
    { name: '동탄신도시 금강펜테리움 7차', dong: '신동' },
    { name: '동탄파크릭스 A51-1BL', dong: '신동' },
    { name: '동탄파크릭스 A51-2BL', dong: '신동' },
    { name: '동탄파크릭스 A52BL', dong: '신동' },
    { name: '동탄파크릭스 A55BL', dong: '신동' },
    { name: '숨마데시앙', dong: '신동' },
    { name: '아테라 파밀리에', dong: '신동' },
    { name: '호반써밋 동탄', dong: '신동' },
    { name: '화성동탄2 제일풍경채 퍼스트', dong: '신동' },
    { name: '힐스테이트 동탄포레', dong: '신동' },
    { name: 'e편한세상 동탄 파크아너스', dong: '신동' },
  ],
  '여울동': [
    { name: '동탄2신도시 금강펜테리움', dong: '여울동' },
    { name: '동탄2신도시 동탄역 대방엘리움', dong: '여울동' },
    { name: '동탄2신도시 동탄역 디에트르', dong: '여울동' },
    { name: '동탄역 남해오네띠 더테라스', dong: '여울동' },
    { name: '동탄역 더샵 센트럴시티 2차', dong: '여울동' },
    { name: '동탄역 동원로얄듀크 비스타 3차', dong: '여울동' },
    { name: '동탄역 롯데캐슬', dong: '여울동' },
    { name: '동탄역 린스트라우스', dong: '여울동' },
    { name: '동탄역 반도유보라 아이비파크 5.0', dong: '여울동' },
    { name: '동탄역 반도유보라 아이비파크 6.0', dong: '여울동' },
    { name: '동탄역 반도유보라 아이비파크 7.0', dong: '여울동' },
    { name: '동탄역 반도유보라 아이비파크 8.0', dong: '여울동' },
    { name: '동탄역 삼정그린코아', dong: '여울동' },
    { name: '동탄역 신미주', dong: '여울동' },
    { name: '동탄역 에미지 시그너스', dong: '여울동' },
    { name: '동탄역 에일린의뜰', dong: '여울동' },
    { name: '동탄역 유림노르웨이숲', dong: '여울동' },
    { name: '동탄역 중흥에스클래스', dong: '여울동' },
    { name: '동탄역 파라곤', dong: '여울동' },
    { name: '동탄역 헤리엇', dong: '여울동' },
    { name: '동탄풍성신미주', dong: '여울동', householdCount: 538, yearBuilt: '2005', brand: '풍성주택' },
    { name: '반도유보라 아이비파크 3', dong: '여울동' },
    { name: '센트럴힐조 동탄', dong: '여울동' },
    { name: '중흥에스클래스 더테라스 리비에르', dong: '여울동' },
    { name: '중흥에스클래스 더테라스 리에스', dong: '여울동' },
    { name: '중흥에스클래스 더테라스 리치', dong: '여울동' },
    { name: 'e편한세상 동탄역 어반원', dong: '여울동' },
  ],
  '영천동': [
    { name: '동탄 중흥에스클래스 파크뷰', dong: '영천동' },
    { name: '동탄 파크자이', dong: '영천동' },
    { name: '동탄 파크푸르지오', dong: '영천동' },
    { name: '동탄 파크한양수자인', dong: '영천동' },
    { name: '동탄 퍼스트파크', dong: '영천동' },
    { name: '동탄 행복마을 푸르지오', dong: '영천동' },
    { name: '동탄2신도시 동원로얄듀크', dong: '영천동' },
    { name: '동탄역 경남아너스빌', dong: '영천동' },
    { name: '동탄역 금강펜테리움 더시티', dong: '영천동' },
    { name: '동탄역 대방디엠시티 더센텀', dong: '영천동' },
    { name: '동탄역 반도유보라 아이비파크 2.0', dong: '영천동' },
    { name: '동탄역 센트럴상록아파트', dong: '영천동' },
    { name: '동탄역 센트럴예미지', dong: '영천동' },
    { name: '동탄역 센트럴자이', dong: '영천동' },
    { name: '동탄역 원로얄듀크 1차', dong: '영천동' },
    { name: '동탄역 이지더원', dong: '영천동' },
    { name: '동탄역 포레너스', dong: '영천동' },
    { name: '동탄역 푸르지오', dong: '영천동', householdCount: 832, yearBuilt: '2017', brand: '대우건설' },
    { name: '힐스테이트 동탄역', dong: '영천동', householdCount: 443, yearBuilt: '2020', brand: '현대건설' },
  ],
  '장지동': [
    { name: '금호어울림 레이크', dong: '장지동', householdCount: 812, yearBuilt: '2018', brand: '금호산업' },
    { name: '금호어울림 레이크 2차', dong: '장지동', householdCount: 681, yearBuilt: '2019', brand: '금호건설' },
    { name: '동탄 레이크 자연앤푸르지오', dong: '장지동' },
    { name: '동탄 레이크파크 자연앤e편한세상', dong: '장지동' },
    { name: '동탄2 롯데캐슬', dong: '장지동' },
    { name: '동탄2 아이파크 1단지', dong: '장지동' },
    { name: '동탄2 아이파크 2단지', dong: '장지동' },
    { name: '동탄2신도시 호반베르디움', dong: '장지동' },
    { name: '동탄호수 자이파밀리에', dong: '장지동' },
    { name: '동탄호수 하우스디', dong: '장지동' },
    { name: '동탄호수공원 계룡리슈빌', dong: '장지동' },
    { name: '동탄호수공원 아이파크', dong: '장지동' },
    { name: '레이크 반도유보라 아이비파크 9.0', dong: '장지동' },
    { name: '제일풍경채 에듀앤파크', dong: '장지동' },
    { name: '한화포레나 동탄호수', dong: '장지동' },
  ],
  '청계동': [
    { name: '동탄역 대원칸타빌 포레지움', dong: '청계동' },
    { name: '동탄역 더힐', dong: '청계동' },
    { name: '동탄역 롯데캐슬 알바트로스', dong: '청계동' },
    { name: '동탄역 모아미래도', dong: '청계동' },
    { name: '동탄역 센트럴 푸르지오', dong: '청계동' },
    { name: '동탄역 시범 금강펜테리움 센트럴파크 3', dong: '청계동' },
    { name: '동탄역 시범 대원칸타빌', dong: '청계동' },
    { name: '동탄역 시범 더샵 센트럴시티', dong: '청계동' },
    { name: '동탄역 시범 리슈빌', dong: '청계동' },
    { name: '동탄역 시범 반도유보라 아이비파크 1.0', dong: '청계동' },
    { name: '동탄역 시범 반도유보라 아이비파크 4.0', dong: '청계동' },
    { name: '동탄역 시범 예미지', dong: '청계동' },
    { name: '동탄역 시범 우남퍼스트빌', dong: '청계동' },
    { name: '동탄역 시범 한화꿈에그린 프레스티지', dong: '청계동' },
    { name: '동탄역 시범 호반써밋', dong: '청계동' },
    { name: '동탄역 신안인스빌리베라 1차', dong: '청계동' },
    { name: '동탄역 신안인스빌리베라 2차', dong: '청계동' },
    { name: '동탄역 호반써밋', dong: '청계동' },
    { name: '동탄역 KCC스위첸', dong: '청계동' },
  ],
};

/** 전체 아파트 수 */
export const TOTAL_APARTMENTS = Object.values(APARTMENTS_BY_DONG).flat().length;
